# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# compile CXX with /usr/bin/c++
CXX_FLAGS = -fPIC -I/home/user/dev/NewGas/trunk/cmake/Plugin_GasFactory    -Wall

CXX_DEFINES = -DPlugin_Shell_EXPORTS

