#! /bin/sh

# chkconfig: 2345 20 80

### BEGIN INIT INFO
# Provides:          brainboxes-usb
# Required-Start:    udev
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Load ftdi_sio module and set it up to recognise Brainboxes product IDs
# Description: Load ftdi_sio module and set it up to recognise Brainboxes product IDs
### END INIT INFO

# Run this shell script to load the ftdi_sio module and configure it to 
# recognise Brainboxes product IDs.
# You probably want to run this script every time at start up.  You can do 
# this using the System V style init system, as follows (log in as root or
# use sudo):
# 1/ Copy this script into /etc/init.d and use chmod to make it executable:
#         chmod +x /etc/init.d/brainboxes-usb
# 2a/ On Debian-type systems, use this command to add this script to the init system:
#         update-rc.d brainboxes-usb defaults
# 2b/ Redhat and SuSE Linux use a program called chkconfig instead:
#         /sbin/chkconfig --add brainboxes-usb
# 2c/ On systems where these programs are not available, you can use 
#     runlevel editors such as sysv-rc-conf and bum instead, or create the 
#     link directly:
#         cd /etc
#         ln -s ../init.d/brainboxes-usb rcS.d/S20brainboxes-usb
#     adjusting the sequence number '20' if neccessary so that it is greater 
#     than the sequence number of the udev start script.  If your system has
#     no /etc/rcS.d directory, you'll have to create links in /etc/rc2.d, 
#     /etc/rc3.d, /etc/rc4.d and /etc/rc5.d instead.

N=/etc/init.d/brainboxes-usb

set -e

case "$1" in
  start)
    /sbin/modprobe ftdi_sio
    echo 05d1 1001 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 1002 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 1003 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 1004 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 1011 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 1013 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 1019 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 1089 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 10ed > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 2001 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 2002 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 2003 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 2011 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 2012 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 2021 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 2022 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 2023 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 2024 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 3011 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 3012 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 5001 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 5002 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 6001 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 7001 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 8001 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 8002 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 8003 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 8004 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 9001 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 9002 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 9003 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 9004 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 9005 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 9006 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 9007 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    echo 05d1 9008 > /sys/bus/usb-serial/drivers/ftdi_sio/new_id
    ;;
  stop|reload|restart|force-reload|status)
    ;;
  *)
    echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
    exit 1
    ;;
esac

exit 0
